### ISSUE TITLE
publish for 2.12, please?

### ISSUE THREAD

**Issue by jozic** [softwaremill/undelay#1]

**Comment by jozic** [comment]
@adamw
do you guys want to adopt this small thing as a companion of odelay?

**Comment by adamw** [comment]
I can publish it under our groupId, but no promises around maintenance :)

**Comment by jozic** [comment]
sounds good to me, I don't think it needs much maintenance anyway
thanks!
please let me know if I can help

**Comment by jozic** [comment]
@adamw any progress here? Can I help somehow? I guess I can send a PR to your fork with packages rename
unless @softprops wants to move ownership of this repo

**Comment by adamw** [comment]
@softprops I guess easiest would be moving ownership like before - could you do it?

**Comment by softprops** [comment]
sry for dropping the ball on this. which org/user should I transfer ownership to?

**Comment by adamw** [comment]
@softprops to the `softwaremill` org please :)

**Comment by softprops** [comment]
@adamw I'm seeing this when I do that 
![screen shot 2018-06-15 at 5 18 25 am](https://user-images.githubusercontent.com/2242/41460723-97170e24-705b-11e8-8463-d113257f4650.png)

I think its because its an org I'm not a member of. Could I just transfer to you and you can transfer it to that org?

**Comment by adamw** [comment]
Ah, sure, go ahead

**Comment by softprops** [comment]
transfer request sent

**Comment by adamw** [comment]
Here you go: https://repo1.maven.org/maven2/com/softwaremill/undelay/

**Comment by softprops** [comment]
Thanks for stepping up on that @adamw!

**Comment by jozic** [comment]
thank you guys!
